Added rule engine controller
ShvaykaD/thingsboard pull request #30
Opened 2024-04-23 13:34 UTC by irynamatveieva

## Pull Request description

Added rule engine controller, service and rest call reply node. Also provided corresponding tests for them. 

## General checklist

- [x] You have reviewed the guidelines [document](https://docs.google.com/document/d/1wqcOafLx5hth8SAg4dqV_LV3un3m5WYR8RdTJ4MbbUM/edit?usp=sharing).
- [ ] [Labels](https://docs.github.com/en/issues/using-labels-and-milestones-to-track-work/managing-labels#about-labels) that classify your pull request have been added.
- [ ] The [milestone](https://docs.github.com/en/issues/using-labels-and-milestones-to-track-work/about-milestones) is specified and corresponds to fix version.  
- [x] Description references specific [issue](https://github.com/thingsboard/thingsboard/issues).
- [x] Description contains human-readable scope of changes.
- [x] Description contains brief notes about what needs to be added to the documentation.
- [x] No merge conflicts, commented blocks of code, code formatting issues.
- [x] Changes are backward compatible or upgrade script is provided.
- [ ] Similar PR is opened for PE version to simplify merge. Crosslinks between PRs added. Required for internal contributors only.

## Back-End feature checklist

- [x] Added corresponding unit and/or integration test(s). Provide written explanation in the PR description if you have failed to add tests.
- [x] If new dependency was added: the dependency tree is checked for conflicts.
- [x] If new service was added: the service is marked with corresponding @TbCoreComponent, @TbRuleEngineComponent, @TbTransportComponent, etc.
- [x] If new REST API was added: the RestClient.java was updated, issue for [Python REST client](https://github.com/thingsboard/thingsboard-python-rest-client) is created.
- [x] If new yml property was added: make sure a description is added (above or near the property).

2024-05-06 08:36 UTC, ShvaykaD commented on application/src/main/java/org/thingsboard/server/controller/RuleEngineController.java
> +                            response -> reply(new LocalRequest(msg, currentUser, result), response));
```suggestion
                            reply -> reply(new LocalRequestMetaData(msg, currentUser, result), reply));
```

2024-05-06 08:40 UTC, ShvaykaD commented on application/src/main/java/org/thingsboard/server/controller/RuleEngineController.java
> +    private record LocalRequest(TbMsg msg, SecurityUser user, DeferredResult<ResponseEntity> responseWriter) {}
```suggestion
    private record LocalRequest(TbMsg request, SecurityUser user, DeferredResult<ResponseEntity> responseWriter) {}
```

2024-05-06 08:52 UTC, ShvaykaD commented on application/src/main/java/org/thingsboard/server/service/ruleengine/RuleEngineCallService.java
> +    void processRestAPICallToRuleEngine(TenantId tenantId, UUID requestId, TbMsg request, boolean useQueueFromTbMsg, Consumer<TbMsg> response);
```suggestion
    void processRestAPICallToRuleEngine(TenantId tenantId, UUID requestId, TbMsg request, boolean useQueueFromTbMsg, Consumer<TbMsg> responseConsumer);
```

2024-05-06 08:56 UTC, ShvaykaD commented on application/src/main/java/org/thingsboard/server/service/ruleengine/DefaultRuleEngineCallService.java
> +        rpcCallBackExecutor = Executors.newSingleThreadScheduledExecutor(ThingsBoardThreadFactory.forName("re-rpc-callback"));
```suggestion
        rpcCallBackExecutor = Executors.newSingleThreadScheduledExecutor(ThingsBoardThreadFactory.forName("re-rest-callback"));
```

2024-05-06 08:56 UTC, ShvaykaD commented on application/src/main/java/org/thingsboard/server/service/ruleengine/DefaultRuleEngineCallService.java
> +    public void processRestAPICallToRuleEngine(TenantId tenantId, UUID requestId, TbMsg request, boolean useQueueFromTbMsg, Consumer<TbMsg> response) {
```suggestion
    public void processRestApiCallToRuleEngine(TenantId tenantId, UUID requestId, TbMsg request, boolean useQueueFromTbMsg, Consumer<TbMsg> response) {
```

2024-05-06 09:53 UTC, ShvaykaD commented on common/proto/src/main/proto/queue.proto
> +  RestApiCallResponseMsgProto restApiCallResponseMsg = 14;
```suggestion
  RestApiCallResponseMsgProto restApiCallResponseMsg = 50;
```

2024-05-06 09:58 UTC, ShvaykaD commented on rule-engine/rule-engine-components/src/test/java/org/thingsboard/rule/engine/rest/TbSendRestApiCallReplyNodeTest.java
> +        TbMsg msg = TbMsg.newMsg(null, TbMsgType.REST_API_REQUEST, DEVICE_ID, new TbMsgMetaData(metadata), data);
```suggestion
        TbMsg msg = TbMsg.newMsg(TbMsgType.REST_API_REQUEST, DEVICE_ID, new TbMsgMetaData(metadata), data);
```

2024-05-06 09:59 UTC, ShvaykaD commented on rule-engine/rule-engine-components/src/test/java/org/thingsboard/rule/engine/rest/TbSendRestApiCallReplyNodeTest.java
> +        verify(rpcServiceMock).sendRestApiCallReply(eq("tb-core-0"), eq(requestUUID), eq(msg));
```suggestion
        verify(rpcServiceMock).sendRestApiCallReply("tb-core-0", requestUUID, msg);
```

2024-05-06 10:00 UTC, ShvaykaD commented on rule-engine/rule-engine-components/src/test/java/org/thingsboard/rule/engine/rest/TbSendRestApiCallReplyNodeTest.java
> +        verify(ctxMock).tellSuccess(eq(msg));
```suggestion
        verify(ctxMock).tellSuccess(msg);
```

2024-05-06 10:03 UTC, ShvaykaD commented on rule-engine/rule-engine-components/src/test/java/org/thingsboard/rule/engine/rest/TbSendRestApiCallReplyNodeTest.java
> +        node.init(ctxMock, configuration);
Please add test for default config.

2024-05-06 10:07 UTC, ShvaykaD commented on rule-engine/rule-engine-components/src/test/java/org/thingsboard/rule/engine/rest/TbSendRestApiCallReplyNodeTest.java
> +}
parameterized test with msg metadata and expected error message. There should be 3 test cases.

2024-05-06 10:09 UTC, ShvaykaD commented on rule-engine/rule-engine-components/src/test/java/org/thingsboard/rule/engine/rest/TbSendRestApiCallReplyNodeTest.java
> +        TbMsg msg = TbMsg.newMsg(null, TbMsgType.REST_API_REQUEST, DEVICE_ID, TbMsgMetaData.EMPTY, TbMsg.EMPTY_STRING);
```suggestion
        TbMsg msg = TbMsg.newMsg(TbMsgType.REST_API_REQUEST, DEVICE_ID, TbMsgMetaData.EMPTY, TbMsg.EMPTY_STRING);
```

2024-05-06 10:09 UTC, ShvaykaD commented on rule-engine/rule-engine-components/src/test/java/org/thingsboard/rule/engine/rest/TbSendRestApiCallReplyNodeTest.java
> +        TbMsg msg = TbMsg.newMsg(null, TbMsgType.REST_API_REQUEST, DEVICE_ID, new TbMsgMetaData(metadata), TbMsg.EMPTY_STRING);
```suggestion
        TbMsg msg = TbMsg.newMsg(TbMsgType.REST_API_REQUEST, DEVICE_ID, new TbMsgMetaData(metadata), TbMsg.EMPTY_STRING);
```

2024-05-06 10:12 UTC, ShvaykaD commented on rule-engine/rule-engine-components/src/test/java/org/thingsboard/rule/engine/rest/TbSendRestApiCallReplyNodeTest.java
> +        node.init(ctxMock, configuration);
also please add a test when the user set non-default fields:

        configuration.setRequestIdMetaDataAttribute("some_custom_request_id_field");
        configuration.setServiceIdMetaDataAttribute("some_custom_service_id_field");

2024-05-06 10:27 UTC, ShvaykaD commented on application/src/test/java/org/thingsboard/server/controller/RuleEngineControllerTest.java
> +        MvcResult result = doPost("/api/rule-engine/", (Object) REQUEST_BODY).andReturn();
we need to add new method. doPostAsyncWithTypedResponse. See doPostWithTypedResponse as an example.

2024-05-06 10:30 UTC, ShvaykaD commented on application/src/test/java/org/thingsboard/server/controller/RuleEngineControllerTest.java
> +        MvcResult result = doPost("/api/rule-engine/", (Object) REQUEST_BODY).andReturn();
should be:

```
        ResponseEntity response = doPostAsyncWithTypedResponse("/api/rule-engine/", REQUEST_BODY, new TypeReference<>() {
        }, status().isOk());
```

2024-05-06 10:42 UTC, ShvaykaD commented on application/src/test/java/org/thingsboard/server/controller/RuleEngineControllerTest.java
> +        MvcResult result = doPost("/api/rule-engine/", (Object) REQUEST_BODY).andReturn();
We need to add to the AbstractWebTest logic that will set sys admin user id to some variable. Use @BeforeClass  to do that.

2024-05-06 10:43 UTC, ShvaykaD commented on application/src/test/java/org/thingsboard/server/controller/RuleEngineControllerTest.java
> +        assertThat(tbMsg.getType()).isEqualTo(msg.getType());
We need to verify that tbMsg.getOriginator() is sys admin user id

2024-05-06 12:00 UTC, ShvaykaD commented on application/src/test/java/org/thingsboard/server/controller/RuleEngineControllerTest.java
> +public class RuleEngineControllerTest extends AbstractControllerTest {
in each test we need to check that auditLogService is called. We should have some existing methods in parent classes that should check this. See AbstractNotifyEntityTest.

2024-05-06 12:07 UTC, ShvaykaD commented on application/src/test/java/org/thingsboard/server/controller/RuleEngineControllerTest.java
> +        doPost("/api/customer/" + customerId.getId() + "/device/" + deviceIdStr).andReturn();
please move to the method in the abstract class at the same level as the createDevice("test", "123"); method.

2024-05-06 12:07 UTC, ShvaykaD commented on application/src/test/java/org/thingsboard/server/controller/RuleEngineControllerTest.java
> +        doPost("/api/customer/" + customerId.getId() + "/device/" + deviceIdStr).andReturn();
assignDeviceToCustomer

2024-05-06 12:09 UTC, ShvaykaD commented on application/src/test/java/org/thingsboard/server/controller/RuleEngineControllerTest.java
> +        doPost("/api/customer/" + customerId.getId() + "/device/" + deviceIdStr).andReturn();
do not do andReturn() if it isn't needed.

2024-05-06 12:11 UTC, ShvaykaD commented on application/src/test/java/org/thingsboard/server/controller/RuleEngineControllerTest.java
> +        doAnswer(invocation -> {
let's move this to the method. We call this in 4 places. Something like mockSuccessfulRestApiCallToRuleEngine.

2024-05-06 12:26 UTC, ShvaykaD commented on application/src/test/java/org/thingsboard/server/service/queue/DefaultTbCoreConsumerServiceTest.java
> +        var restApiCallResponseMsgProto = TransportProtos.RestApiCallResponseMsgProto.newBuilder().build();
.newBuilder().build() -> defaultInstance

2024-05-06 12:28 UTC, ShvaykaD commented on application/src/test/java/org/thingsboard/server/service/queue/DefaultTbCoreConsumerServiceTest.java
> +        doNothing().when(ruleEngineCallServiceMock).onQueueMsg(restApiCallResponseMsgProto, tbCallbackMock);
Does it do something?

2024-05-06 12:41 UTC, ShvaykaD commented on application/src/test/java/org/thingsboard/server/service/rpc/DefaultTbRuleEngineRpcServiceTest.java
> +class DefaultTbRuleEngineRpcServiceTest {
Let's create an instance of TbRuleEngineDeviceRpcService

2024-05-06 12:42 UTC, ShvaykaD commented on application/src/test/java/org/thingsboard/server/service/rpc/DefaultTbRuleEngineRpcServiceTest.java
> +class DefaultTbRuleEngineRpcServiceTest {
Try  @InjectMocks

2024-05-06 13:04 UTC, ShvaykaD commented on application/src/test/java/org/thingsboard/server/service/ruleengine/DefaultRuleEngineCallServiceTest.java
> +        assertThat(requests.size()).isEqualTo(1);
verify the value of request

2024-05-06 13:20 UTC, ShvaykaD commented on application/src/test/java/org/thingsboard/server/service/ruleengine/DefaultRuleEngineCallServiceTest.java
> +        assertThat(requests.size()).isEqualTo(0);
Awaitility.await("Await until request was deleted from map due to timeout")
                .pollDelay(25, TimeUnit.MILLISECONDS)
                .atMost(30, TimeUnit.SECONDS)
                .until(requests::isEmpty);

2024-05-06 13:30 UTC, ShvaykaD requested changes
Please see my comments added above.

2024-05-09 07:47 UTC, irynamatveieva commented on rule-engine/rule-engine-components/src/test/java/org/thingsboard/rule/engine/rest/TbSendRestApiCallReplyNodeTest.java
> +}
Need to add 4 test cases here (also including test case with message data)

2024-08-02 06:52 UTC, closed without merging